### ISSUE TITLE
Make 1.1.0 available on Cocoapods

### ISSUE THREAD

**Issue by JohannesRudolph** [kickingvegas/YmsCoreBluetooth#113]
1.1 lgtm, would you mind pushing it onto cocoapods.org?

**Comment by kickingvegas** [comment]
Danged. Got burned by semantic versioning. 1.1.0 < 1.09.1. Will fix.

Thanks for pointing this out!

**Comment by JohannesRudolph** [comment]
Great, seems this is available now, can be closed!
